
spring.application.name=swp391
server.port=8080

# Local
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# Hibernate will create/update tables from the JPA entities automatically.
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
spring.cloud.config.import-check.enabled=false
app.otp.expiration-minutes=${OTP_EXPIRATION_MINUTES:10}
app.mail.from=${MAIL_FROM:${SPRING_MAIL_USERNAME:no-reply@example.com}}

#jira(project admin)
jira.base-url=${JIRA_BASE_URL}
jira.admin-email=${JIRA_ADMIN_EMAIL}
jira.api-token=${JIRA_API_TOKEN}
jira.org-id=${ATLASSIAN_ORG_ID}

#github
github.base-url=${GITHUB_BASE_URL:https://api.github.com}
github.org=${GITHUB_ORG}
github.admin-token=${GITHUB_ADMIN_TOKEN}

#github oauth (user verify)
github.oauth.client-id=${GITHUB_CLIENT_ID}
github.oauth.client-secret=${GITHUB_CLIENT_SECRET}
github.oauth.redirect-uri=${GITHUB_REDIRECT_URI}

#jira oauth (user verify)
jira.oauth.client-id=${JIRA_CLIENT_ID}
jira.oauth.client-secret=${JIRA_CLIENT_SECRET}
jira.oauth.redirect-uri=${JIRA_REDIRECT_URI}

#mail
spring.mail.host=${MAIL_HOST:}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_SMTP_STARTTLS_REQUIRED:true}

spring.config.import=optional:file:.env[.properties]
